export const ActionID = {
  initSDK: 'initSDK',
  getUserInfo: 'getUserInfo',
  requestCamera: 'requestCamera',
  requestPhoto: 'requestPhoto',
  goHome: 'goHome',
  goBack: 'goBack',
  openUrl: 'openUrl',
  openWeb: 'openWeb',
  dismissAll: 'dismissAll',
  dismiss: 'dismiss',
  hideLoading: 'hideLoading',
  showLoading: 'showLoading',
  setDataStorage: 'setDataStorage',
  getDataStorage: 'getDataStorage',
  deleteDataStorage: 'deleteDataStorage',
  showDialog: 'showDialog',
  showToast: 'showToast',
};