export const ActionID = {
  initSDK: 'initSDK',
  destroySDK: 'destroySDK',
  getUserInfo: 'getUserInfo',
  requestPermission: 'requestPermission',
  checkPermission: 'checkPermission',
  requestCamera: 'requestCamera',
  requestPhoto: 'requestPhoto',
  goHome: 'goHome',
  goBack: 'goBack',
  openUrl: 'openUrl',
  openWeb: 'openWeb',
  dismissAll: 'dismissAll',
  dismiss: 'dismiss',
  hideLoading: 'hideLoading',
  showLoading: 'showLoading',
  setDataStorage: 'setDataStorage',
  getDataStorage: 'getDataStorage',
  deleteStorageKey: 'deleteStorageKey',
  deleteAppStorage: 'deleteAppStorage',
  showDialog: 'showDialog',
  showToast: 'showToast',
  requestDeposit: 'requestDeposit',
  requestWithDraw: 'requestWithDraw'
}
